In [1]:
import numpy as np

## numpy简介
NumPy是Python语言的一个扩充程序库。支持高级大量的维度数组与矩阵运
算，此外也针对数组运算提供大量的数学函数库。

#### 基本功能
* 快速高效的多维数组对象ndarray  
* 用于对数组执行元素级计算以及直接对数组执行数学运算的函数  
* 用于读写硬盘上基于数组的数据集的工具
* 线性代数运算、傅里叶变换，以及随机数生成
* 用于将C、C++、Fortran代码集成到Python的工具
* 除了为Python提供快速的数组处理能力，NumPy在数据分析方面还有另外一
个主要作用，即作为在算法之间传递数据的容器。

## 创建numpy.ndarray对象(Greating ndarrays)

最简单的方法使用array函数，输入一个序列即可，比如list：

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
type(arr1)

numpy.ndarray

嵌套序列能被转换为多维数组：

In [4]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

因为data2是一个list of lists, 所以arr2维度为2。我们能用ndim和shape属性来确认一下：

In [5]:
arr2.ndim

2

In [6]:
arr2.shape

(2, 4)

除非主动声明，否则np.array会自动给data搭配适合的类型，并保存在dtype里：

In [7]:
arr1.dtype

dtype('float64')

In [8]:
arr2.dtype

dtype('int32')

arange是一个numpy版的range函数：

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
%time l = [n for n in range(10**8)]

Wall time: 5.47 s


In [11]:
%time arr = np.arange(10**8)

Wall time: 149 ms


**numpy 常用的ndarray创建函数**

| 类型              | 说明                                                                                                                  |
| ----------------- | --------------------------------------------------------------------------------------------------------------------- |
| array             | 将输入数据（列表、元组、数组或其它序列类型）转换为ndarray。要么推断出dtype，要么显示指定dtype。默认直接复制输入数据。 |
| asarray           | 将输入转换为darray，如果输入本身就是一个ndarray就不进行复制。                                                         |
| arange            | 类似于内置的range，但返回一个ndarray而不是列表。                                                                      |
| ones, ones_like   | 根据指定形状和dtype创建一个全1数组。ones_like以另一个数组为参数，并根据其形状和dtype创建一个全1数组。                 |
| zeros, zeros_like | 类似于ones和ones_like，只不过产生的是全0数组而已。                                                                    |
| empty, empty_like | 创建数组，只分配内存空间但不填充任何值。                                                                              |
| eye, identity     | 创建一个正方的N * N单位矩阵                                                                                           |

In [12]:
np.zeros(10) # 生成包含10个0的一维数组

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3, 6)) # 生成3*6的二维数组

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.empty((2, 3, 2)) # 生成2*3*2的三维数组，所有元素未初始化。

array([[[1.03478477e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 5.64233733e-067]],

       [[6.50815467e-091, 9.41706229e-047],
        [1.55071385e+184, 6.17582558e-042],
        [3.99910963e+252, 1.04718130e-142]]])

In [15]:
# 创建一个5个元素的数组，这5个数均匀地分配到0~1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# 创建一个3×3的、在0~1均匀分布的随机数组成的数组
np.random.random((3, 3))

array([[0.36713613, 0.44295819, 0.57964964],
       [0.21232805, 0.86532721, 0.8400068 ],
       [0.71368448, 0.15850965, 0.89326735]])

In [17]:
# 创建一个3×3的、均值为0、方差为1的
# 正态分布的随机数数组
np.random.normal(0, 1, (3, 3))

array([[ 9.10883145e-01,  5.82738464e-01, -8.36840529e-01],
       [ 1.43911596e+00,  4.71641446e-01, -1.61334787e-03],
       [ 8.12855873e-01, -2.44316997e-01, -2.88671820e+00]])

In [18]:
# 创建一个3×3的、[0, 10)区间的随机整型数组
np.random.randint(0, 10, (3, 3))

array([[5, 1, 7],
       [7, 8, 2],
       [7, 3, 0]])

In [19]:
# 创建一个3×3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# 创建一个由3个整型数组成的未初始化的数组
# 数组的值是内存空间中的任意值
np.empty(3)

array([1., 1., 1.])

## NumPy数组的属性

数组的属性：确定数组的大小、形状、存储大小、数据类型。

首先介绍一些有用的数组属性。定义三个随机的数组：一个一维数组、一个二维数组和一
个三维数组。我们将用NumPy 的随机数生成器设置一组种子值，以确保每次程序执行时
都可以生成同样的随机数组：

In [21]:
np.random.seed(0) # 设置随机数种子
x1 = np.random.randint(10, size=6) # 一维数组
x2 = np.random.randint(10, size=(3, 4)) # 二维数组
x3 = np.random.randint(10, size=(3, 4, 5)) # 三维数组

每个数组有nidm（数组的维度）、shape（数组每个维度的大小）和 size（数组的总大小）属性：

In [22]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


另外一个有用的属性是dtype：

In [23]:
print("dtype:", x3.dtype)

dtype: int32


其他的属性包括表示每个数组元素字节大小的itemsize，以及表示数组总字节大小的属性
nbytes：

In [24]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


一般来说，可以认为nbytes 跟itemsize 和size 的乘积大小相等。

## numpy数据类型(Data Types for ndarrays)

**numpy数据类型I**

| 类型 说明              |                                                      |
| ---------------------- | ---------------------------------------------------- |
| int8, uint8 - i1, u1   | 有／无符号的8位整型                                  |
| int16, uint16 - i2, u2 | 有／无符号的16位整型                                 |
| int32, uint32 - i4, u4 | 有／无符号的32位整型                                 |
| int64, uint64 - i8, u8 | 有／无符号的64位整型                                 |
| float16 - f2           | 半精度浮点数                                         |
| float32 - f4 or f      | 标准的单精度浮点数，与C的float兼容。                 |
| float64 - f8 or d      | 标准的双精度浮点数。与C的double和Python的float兼容。 |
| float128 - f16 or g    | 扩展精度浮点数                                       |

**numpy数据类型II**

| 类型                        | 说明                                            |
| --------------------------- | ----------------------------------------------- |
| complex64/128/256 -c8/16/32 | 分别用两个32位，64位或128位浮点数表示的复数。   |
| bool - ?                    | 存储True和False值的布尔类型                     |
| object - O                  | Python对象类型                                  |
| string_ - S                 | 固定长度的字符串类型。S10代表长度为10的字符串。 |
| unicode_ - U                | 固定长度的unicode类型                           |

生成数组时指定数据类型

In [25]:
arr = np.array([1, 2, 3], dtype = np.float64)
arr.dtype

dtype('float64')

In [26]:
arr = np.array([1, 2, 3], dtype = np.int32)
arr.dtype

dtype('int32')

使用astype复制数组并转换数据类型

In [27]:
int_arr = np.array([1, 2, 3, 4, 5])
float_arr = int_arr.astype(np.float)
print(int_arr.dtype)
print(float_arr.dtype)

int32
float64


使用astype将float转换为int时小数部分被舍弃

In [28]:
float_arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
int_arr = float_arr.astype(dtype = np.int)
int_arr

array([ 3, -1, -2,  0, 12, 10])

使用astype把字符串转换为数组，如果失败抛出异常。

In [29]:
str_arr = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
float_arr = str_arr.astype(dtype = np.float)
float_arr

array([ 1.25, -9.6 , 42.  ])

astype使用其它数组的数据类型作为参数

In [30]:
int_arr = np.arange(10)
float_arr = np.array([.23, 0.270, .357, 0.44, 0.5], dtype = np.float64)
print(int_arr.astype(float_arr.dtype))
print(int_arr[0], int_arr[1])  # astype做了复制，数组本身不变。

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
0 1


还可以利用类型的缩写，比如u4就代表unit32：

In [31]:
empty_unit32 = np.empty(8, dtype='u4')
empty_unit32

array([         0, 1070596096,          0, 1071644672,          0,
       1072168960,          0, 1072693248], dtype=uint32)

记住，astype总是会返回一个新的数组

## 数组的基本计算(Arithmetic with NumPy Arrays)

数组之所以重要，是因为不用写for循环就能表达很多操作，这种特性叫做vectorization(向量化)。任何两个大小相等的数组之间的运算，都是element-wise（点对点）：

In [32]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [34]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

element-wise 我翻译为点对点，就是指两个数组的运算，在同一位置的元素间才会进行运算。

这种算数操作如果涉及标量（scalar）的话，会涉及到数组的每一个元素：

In [35]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [36]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [37]:
arr + 10

array([[11., 12., 13.],
       [14., 15., 16.]])

两个数组的比较会产生布尔数组：

In [38]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [39]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## 基本的索引和切片(Basic Indexing and Slicing)

#### 数组索引：获取单个元素

和Python
列表一样，在一维数组中，你也可以通过中括号指定索引获取第i 个值（从0 开始计数）：

In [40]:
x1 = np.random.randint(10, size=6)
x1

array([4, 3, 4, 4, 8, 4])

In [41]:
x1[0]

4

为了获取数组的末尾索引，可以用负值索引：

In [42]:
x1[-1]

4

在多维数组中，可以用逗号分隔的索引元组获取元素：

In [43]:
x2 = np.random.randint(10, size=(3, 4)) # 二维数组
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [44]:
x2[2, -1]

0

也可以用以上索引方式修改元素值：

In [45]:
x2[0, 0] = 99
x2

array([[99,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

请注意，和Python 列表不同，NumPy 数组是固定类型的。这意味着当你试图将一个浮点
值插入一个整型数组时，浮点值会被截短成整型。并且这种截短是自动完成的，不会给你
提示或警告，所以需要特别注意这一点！

In [46]:
x1[0] = 3.14159 # 这将被截短
x1

array([3, 3, 4, 4, 8, 4])

#### 数组切片：获取子数组

正如此前用中括号获取单个数组元素，我们也可以用切片（slice）符号获取子数组，切片
符号用冒号（:）表示。NumPy 切片语法和Python 列表的标准切片语法相同。为了获取数
组x 的一个切片，可以用以下方式：

    x[start:stop:step]
    
如果以上3 个参数都未指定，那么它们会被分别设置默认值start=0、stop= 维度的大小
（size of dimension）和step=1。我们将详细介绍如何在一维和多维数组中获取子数组。

###### 1. 一维子数组

In [47]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
x[:5] # 前五个元素

array([0, 1, 2, 3, 4])

In [49]:
x[5:] # 索引五之后的元素

array([5, 6, 7, 8, 9])

In [50]:
x[4:7] # 中间的子数组

array([4, 5, 6])

In [51]:
x[::2] # 每隔一个元素

array([0, 2, 4, 6, 8])

In [52]:
x[1::2] # 每隔一个元素，从索引1开始

array([1, 3, 5, 7, 9])

你可能会在步长值为负时感到困惑。在这个例子中，start 参数和stop 参数默认是被交换的。因此这是一种非常方便的逆序数组的方式：

In [53]:
x[::-1] # 所有元素，逆序的

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [54]:
x[5::-2] # 从索引5开始每隔一个元素逆序

array([5, 3, 1])

###### 2. 多维子数组

多维切片也采用同样的方式处理，用冒号分隔。例如：

In [55]:
x2

array([[99,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

In [56]:
x2[:2, :3] # 两行，三列

array([[99,  7,  5],
       [ 0,  1,  5]])

In [57]:
x2[:3, ::2] # 所有行，每隔一列

array([[99,  5],
       [ 0,  5],
       [ 3,  5]])

最后，子数组维度也可以同时被逆序：

In [58]:
x2[::-1, ::-1]

array([[ 0,  5,  0,  3],
       [ 9,  5,  1,  0],
       [ 5,  5,  7, 99]])

###### 3. 获取数组的行和列

一种常见的需求是获取数组的单行和单列。你可以将索引与切片组合起来实现这个功能，
用一个冒号（:）表示空切片：

In [59]:
print(x2[:, 0]) # x2的第一列

[99  0  3]


In [60]:
print(x2[0, :]) # x2的第一行

[99  7  5  5]


在获取行时，出于语法的简介考虑，可以省略空的切片：

In [61]:
x2[0] #等于x2[0, :]

array([99,  7,  5,  5])

###### 4. 非副本视图的子数组

关于数组切片有一点很重要也非常有用，那就是数组切片返回的是数组数据的视图，而
不是数值数据的副本。这一点也是NumPy 数组切片和Python 列表切片的不同之处：在
Python 列表中，切片是值的副本。例如此前示例中的那个二维数组：

In [62]:
print(x2)

[[99  7  5  5]
 [ 0  1  5  9]
 [ 3  0  5  0]]


从中抽取一个2×2 的子数组：

In [63]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[99  7]
 [ 0  1]]


现在如果修改这个子数组，将会看到原始数组也被修改了！结果如下所示：

In [64]:
x2_sub[0, 0] = 666
x2_sub

array([[666,   7],
       [  0,   1]])

In [65]:
x2

array([[666,   7,   5,   5],
       [  0,   1,   5,   9],
       [  3,   0,   5,   0]])

这种默认的处理方式实际上非常有用：它意味着在处理非常大的数据集时，可以获取或处
理这些数据集的片段，而不用复制底层的数据缓存。

###### 5. 创建数组的副本

尽管数组视图有一些非常好的特性，但是在有些时候明确地复制数组里的数据或子数组也
是非常有用的。可以很简单地通过copy() 方法实现：

In [66]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[666,   7],
       [  0,   1]])

如果修改这个子数组，原始的数组不会被改变：

In [67]:
x2_sub_copy[0, 0] = 42
x2_sub_copy

array([[42,  7],
       [ 0,  1]])

In [68]:
x2

array([[666,   7,   5,   5],
       [  0,   1,   5,   9],
       [  3,   0,   5,   0]])

## 布尔索引(Boolean Indexing)

* 布尔型数组的长度必须跟被索引的轴长度一致。
* 可以将布尔型数组跟切片、整数（或整数序列）混合使用

假设我们的数组数据里有一些重复。这里我们用numpy.random里的randn函数来随机生成一些离散数据：

In [69]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [70]:
data = np.random.randn(7, 4)
data

array([[ 1.50944508,  1.06777513, -0.68658948,  0.01487332],
       [-0.3756659 , -0.03822364,  0.36797447, -0.0447237 ],
       [-0.30237513, -2.2244036 ,  0.72400636,  0.35900276],
       [ 1.07612104,  0.19214083,  0.85292596,  0.01835718],
       [ 0.42830357,  0.99627783, -0.49114966,  0.71267817],
       [ 1.11334035, -2.15367459, -0.41611148, -1.07089699],
       [ 0.22113881, -1.12305712, -1.05075796,  1.01207905]])

假设每一个name对应data数组中的一行，我们想要选中name为'Bob'的所有行。就像四则运算，用比较运算符（==）：

In [71]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

然后用这个布尔数组当做索引：

In [72]:
data[names == 'Bob']

array([[ 1.50944508,  1.06777513, -0.68658948,  0.01487332],
       [ 1.07612104,  0.19214083,  0.85292596,  0.01835718]])

注意：布尔数组和data数组的长度要一样。

我们可以选中names=='Bob'的行，然后索引列：

In [73]:
data[names == 'Bob', 2:]

array([[-0.68658948,  0.01487332],
       [ 0.85292596,  0.01835718]])

选中除了'Bob'外的所有行，可以用`!=`或者`~`：

In [74]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [75]:
data[~(names == 'Bob')]

array([[-0.3756659 , -0.03822364,  0.36797447, -0.0447237 ],
       [-0.30237513, -2.2244036 ,  0.72400636,  0.35900276],
       [ 0.42830357,  0.99627783, -0.49114966,  0.71267817],
       [ 1.11334035, -2.15367459, -0.41611148, -1.07089699],
       [ 0.22113881, -1.12305712, -1.05075796,  1.01207905]])

当想要反转一个条件时，用~操作符很方便：

In [76]:
cond = names == 'Bob'
data[~cond]

array([[-0.3756659 , -0.03822364,  0.36797447, -0.0447237 ],
       [-0.30237513, -2.2244036 ,  0.72400636,  0.35900276],
       [ 0.42830357,  0.99627783, -0.49114966,  0.71267817],
       [ 1.11334035, -2.15367459, -0.41611148, -1.07089699],
       [ 0.22113881, -1.12305712, -1.05075796,  1.01207905]])

选中2个或3个名字，组合多个布尔条件，用布尔运算符&，|，另外python中的关键词and和or不管用：

In [77]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [78]:
data[mask]

array([[ 1.50944508,  1.06777513, -0.68658948,  0.01487332],
       [-0.30237513, -2.2244036 ,  0.72400636,  0.35900276],
       [ 1.07612104,  0.19214083,  0.85292596,  0.01835718],
       [ 0.42830357,  0.99627783, -0.49114966,  0.71267817]])

**用布尔索引总是会返回一份新创建的数据，原本的数据不会被改变。**

更改值的方式也很直觉。比如我们想让所有负数变为0：

In [79]:
data[data < 0] = 0
data

array([[1.50944508, 1.06777513, 0.        , 0.01487332],
       [0.        , 0.        , 0.36797447, 0.        ],
       [0.        , 0.        , 0.72400636, 0.35900276],
       [1.07612104, 0.19214083, 0.85292596, 0.01835718],
       [0.42830357, 0.99627783, 0.        , 0.71267817],
       [1.11334035, 0.        , 0.        , 0.        ],
       [0.22113881, 0.        , 0.        , 1.01207905]])

用一维的布尔数组也能更改所有行或列：

In [80]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.36797447, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.11334035, 0.        , 0.        , 0.        ],
       [0.22113881, 0.        , 0.        , 1.01207905]])

## 数组的变形：数组维度改变，数组转置和轴交换(Transposing Arrays and Swapping Axes)

#### reshape 数组变形

一个有用的操作类型是数组的变形。数组变形最灵活的实现方式是通过reshape() 函数
来实现。例如，如果你希望将数字1~9 放入一个3×3 的矩阵中，可以采用如下方法：

In [81]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

请注意，如果希望该方法可行，那么原始数组的大小必须和变形后数组的大小一致。如果
满足这个条件，reshape 方法将会用到原始数组的一个非副本视图。但实际情况是，在非
连续的数据缓存的情况下，返回非副本视图往往不可能实现。

In [82]:
arr1 = np.arange(1, 10)
arr2 = arr1.reshape((3, 3))
arr2[0,0] = 9

In [83]:
arr2

array([[9, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr1

array([9, 2, 3, 4, 5, 6, 7, 8, 9])

**用元组设置维度** 除了可以使用reshape函数，我们也可以直接用一个正整数元组来设
置数组的维度，如下所示：

In [85]:
arr2.shape = (9,1) #arr2.shape = (9,)会成一维数组
arr2

array([[9],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

正如你所看到的，这样的做法将直接改变所操作的数组，现在数组arr2成了一个9×1的多维数组。

一个常见的变形模式是将一个一维数组转变为二维的行或列的矩阵。你也可以通过
reshape 方法来实现，或者更简单地在一个切片操作中利用newaxis 关键字：

In [86]:
x = np.array([1, 2, 3])
# 通过变形获得的行向量
x.reshape((1, 3))

array([[1, 2, 3]])

In [87]:
# 通过newaxis获得的行向量
x[np.newaxis, :]

array([[1, 2, 3]])

In [88]:
# 通过变形获得的列向量
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [89]:
# 通过newaxis获得的列向量
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

#### 数组转置和轴交换(Transposing Arrays and Swapping Axes)

 数组转置也是返回一个view，而不是新建一个数组。有两种方式，一个是transpose方法，一个是T属性：

In [90]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

做矩阵计算的时候，这个功能很常用，计算矩阵乘法的时候，用np.dot:

In [92]:
arr = np.arange(8).reshape((4, 2))
print(arr.T)
print(arr)

[[0 2 4 6]
 [1 3 5 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [93]:
np.dot(arr.T, arr)

array([[56, 68],
       [68, 84]])

上面的例子是 (2x4) x (4x2) = (2x2)。得到的结果是2x2维，就是普通的矩阵乘法。

对于多维数组，transpose会接受由轴数字组成的tuple，来交换轴：

In [94]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [95]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

这里，secode axis(1)被设为第一个，first axis(0)第二个，最后的axis没变。

使用.T来转置是swapping axes(交换轴)的一个特殊情况。ndarray有方法叫做swapaxes, 这个方法取两个axis值，并交换这两个轴：

In [96]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [97]:
arr.swapaxes(1, 2) # 直交换second axis和last axis

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

swapaxes也是返回view，不生成新的data。

#### 改变数组的维度的方法

###### (1) reshape

reshape函数的作用是改变数组的“形
状”，也就是改变数组的维度，其参数为一个正整数元组，分别指定数组在每个维度上的大小。
如果指定的维度和数组的元素数目不相吻合，函数将抛出异常。

In [98]:
b = np.arange(24).reshape(2,3,4)
b.shape

(2, 3, 4)

In [99]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

###### (2) ravel

我们可以用ravel函数完成展平的操作：

In [100]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

###### (2) ravel

我们可以用ravel函数完成展平的操作：

In [101]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

###### (3) flatten

这个函数恰如其名，flatten就是展平的意思，与ravel函数的功能相同。
不过，flatten函数会请求分配内存来保存结果，而ravel函数只是返回数组的一个视图（view）：

In [102]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

###### (4) 用元组设置维度

除了可以使用reshape函数，我们也可以直接用一个正整数元组来设
置数组的维度，如下所示：

In [103]:
b.shape = (6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

正如你所看到的，这样的做法将直接改变所操作的数组，现在数组b成了一个6×4的多维数组。

###### (5) transpose

在线性代数中，转置矩阵是很常见的操作。对于多维数组，我们也可以这样做：

In [104]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

###### (6) resize

resize和reshape函数的功能一样，但resize会直接修改所操作的数组：

In [105]:
b.resize((2,12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

## 数组拼接和分裂

以上所有的操作都是针对单一数组的，但有时也需要将多个数组合并为一个，或将一个数
组分裂成多个。接下来将详细介绍这些操作。

#### 1. 数组的拼接

拼接或连接NumPy 中的两个数组主要由np.concatenate、np.vstack 和np.hstack 例程实
现。np.concatenate 将数组元组或数组列表作为第一个参数，如下所示：

In [106]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

你也可以一次性拼接两个以上数组：

In [107]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


np.concatenate 也可以用于二维数组的拼接：

In [108]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])
# 沿着第一个轴拼接
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [109]:
# 沿着第二个轴拼接（从0开始索引）
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

沿着固定维度处理数组时，使用np.vstack（垂直栈）和np.hstack（水平栈）函数会
更简洁：

In [110]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
# 垂直栈数组
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [111]:
# 水平栈数组
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

与之类似，np.dstack 将沿着第三个维度拼接数组。

#### 2. 数组的分裂

与拼接相反的过程是分裂。分裂可以通过np.split、np.hsplit 和np.vsplit 函数来实现。
可以向以上函数传递一个索引列表作为参数，索引列表记录的是分裂点位置：

In [112]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


值得注意的是，N 分裂点会得到N + 1 个子数组。相关的np.hsplit 和np.vsplit 的用法也
类似：

In [113]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [115]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


同样，np.dsplit 将数组沿着第三个维度分裂。